# Generated by Django 4.2.6 on 2023-10-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ice_cream_truck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="stock",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
