# Generated by Django 4.2.6 on 2023-10-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ice_cream_truck", "0002_customer_balance_fooditem_stock_alter_fooditem_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="icecreamtruck",
            name="food_items",
            field=models.ManyToManyField(to="ice_cream_truck.fooditem"),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ice_cream_truck.customer",
                    ),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ice_cream_truck.fooditem",
                    ),
                ),
                (
                    "ice_cream_truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ice_cream_truck.icecreamtruck",
                    ),
                ),
            ],
        ),
    ]
